/**
 * 앱 전용 번역 사전을 공통 i18n factory에 전달한다. Java ResourceBundle의 키 기반 문구 선택과 비슷하다.
 * request/report는 각 기능이 소유한 사전을 합치고 app은 메뉴와 중립 예제 문구를 정의한다.
 * 화면의 t("app.title") 계열 호출은 현재 locale에 맞는 키를 읽는다. 권한·업무 상태 코드 자체를 번역 문자열로 저장하지 않는다.
 */
import { createScI18n } from "@sc/i18n";
import { requirementMessages } from "./features/requirements/messages";
import { requirementReportMessages } from "./features/reports/requirements/messages";
export const i18n = createScI18n({
  messages: {
    ko: {
      request: requirementMessages.ko,
      report: requirementReportMessages.ko,
      app: {
        reference: "레퍼런스",
        navigation: "화면 탐색",
        dashboard: "대시보드",
        examples: "예제 목록",
        login: "로그인",
        logout: "로그아웃",
        start: "프로젝트 시작",
        patterns: "공통 기능 예제",
        admin: "관리",
        account: "내 계정",
        operations: "운영",
        screens: "이미지 작업실",
        kanban: "칸반",
        notices: "공지",
        documents: "서식 문서",
        footer: "공통 모듈을 사용해 화면을 조립합니다.",
        form: "공통 입력 폼",
        title: "제목",
        category: "유형",
        description: "설명",
        accepted: "검토 내용 확인",
        analysis: "분석",
        development: "개발",
        required: "입력해 주세요.",
        acceptRequired: "검토 내용을 확인해 주세요.",
        maxTitle: "제목은 200자 이하여야 합니다.",
        saved: "로컬 검증을 완료했습니다.",
        leave: "저장하지 않은 입력을 버리고 화면을 이동할까요?",
        lineChart: "선 그래프로",
        barChart: "막대 그래프로",
        discard: "작성 중인 입력을 초기화할까요?",
        confirmTitle: "입력 초기화 확인",
        formHint: "폼 상태와 Zod 검증은 이 화면이 소유합니다.",
        table: "정렬·페이지·선택 예제",
        largeTable: "가상 표 10,000행",
        largeList: "가상 목록 10,000행",
        name: "이름",
        amount: "수량",
        chart: "중립 차트",
        chartSummary: "합성 자료 3개의 값을 표로도 확인할 수 있습니다.",
        changeData: "자료 변경",
        selectDatum: "항목 선택",
        selectedDatum: "선택한 항목",
        editor: "서식 입력",
        excel: "엑셀 가져오기·내보내기",
        excelFile: "XLSX 파일",
        staged: "미리보기 자료",
        apply: "예제 자료에 반영",
        clear: "가져오기 취소",
        excelScope: "화면의 예제 자료만 내보냅니다. 서버에 저장하지 않습니다.",
        formNote: "이 예제는 로컬 검증이며 API 저장은 예제 목록 화면에서 확인합니다.",
      },
    },
    en: {
      request: requirementMessages.en,
      report: requirementReportMessages.en,
      app: {
        reference: "Reference",
        navigation: "Navigation",
        dashboard: "Dashboard",
        examples: "Examples",
        login: "Sign in",
        logout: "Sign out",
        start: "Get started",
        patterns: "Common feature examples",
        admin: "Administration",
        account: "My account",
        operations: "Operations",
        screens: "Image workspace",
        kanban: "Kanban",
        notices: "Notices",
        documents: "Rich text documents",
        footer: "Compose screens with shared modules.",
        form: "Shared input form",
        title: "Title",
        category: "Category",
        description: "Description",
        accepted: "Review acknowledged",
        analysis: "Analysis",
        development: "Development",
        required: "Please enter a value.",
        acceptRequired: "Please acknowledge the review.",
        maxTitle: "Title must be 200 characters or fewer.",
        saved: "Local validation completed.",
        leave: "Discard the draft and leave this screen?",
        lineChart: "Line chart",
        barChart: "Bar chart",
        discard: "Reset the draft?",
        confirmTitle: "Confirm draft reset",
        formHint: "This screen owns form state and Zod validation.",
        table: "Sorting, pagination and selection",
        largeTable: "Virtual table: 10,000 rows",
        largeList: "Virtual list: 10,000 rows",
        name: "Name",
        amount: "Quantity",
        chart: "Sample chart",
        chartSummary: "The three sample values are also available in a table.",
        changeData: "Change data",
        selectDatum: "Select datum",
        selectedDatum: "Selected datum",
        editor: "Rich text input",
        excel: "Excel import and export",
        excelFile: "XLSX file",
        staged: "Import preview",
        apply: "Apply to sample data",
        clear: "Cancel import",
        excelScope: "Export the supplied sample rows only. No server write.",
        formNote: "This example validates locally. Use Examples for API saving.",
      },
    },
  },
});
