-- 앱 소유 db2 새 스키마 DDL. 기존 H2 migration은 별도 경로에서 checksum을 보존한다.
CREATE TABLE starter_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200 CODEUNITS32) NOT NULL,
    owner VARCHAR(64 CODEUNITS32) NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1 CHECK (revision>=1),
    updated_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX idx_starter_note_owner_updated ON starter_note(owner,updated_at DESC,id DESC);
