-- 앱 소유 oracle 새 스키마 DDL. 기존 H2 migration은 별도 경로에서 checksum을 보존한다.
CREATE TABLE example_entry (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200 CHAR) NOT NULL,
    revision NUMBER(10) DEFAULT 1 NOT NULL,
    CONSTRAINT example_title_nonblank CHECK (LENGTH(TRIM(title)) > 0),
    CONSTRAINT example_revision_positive CHECK (revision >= 1)
);
