-- 앱 소유 oracle 새 스키마 DDL. 기존 H2 migration은 별도 경로에서 checksum을 보존한다.
CREATE TABLE kanban_member (
    user_id NUMBER(19) PRIMARY KEY REFERENCES reference_user(id)
);
CREATE TABLE kanban_board (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (START WITH 2) PRIMARY KEY,
    title VARCHAR2(100 CHAR) NOT NULL CHECK (LENGTH(title) BETWEEN 1 AND 100),
    author_id NUMBER(19) REFERENCES reference_user(id),
    revision NUMBER(10) DEFAULT 1 NOT NULL CHECK (revision >= 1),
    command_sequence NUMBER(19) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CHECK (id = 1 OR author_id IS NOT NULL)
);
INSERT INTO kanban_board(id,title,author_id,revision,created_at,updated_at)
VALUES (1,'기본 업무',NULL,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
CREATE TABLE kanban_task (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id NUMBER(19) NOT NULL REFERENCES kanban_board(id),
    title VARCHAR2(200 CHAR) NOT NULL,
    description CLOB,
    status VARCHAR2(16 CHAR) NOT NULL CHECK (status IN ('TODO','IN_PROGRESS','DONE','REJECTED')),
    priority VARCHAR2(6 CHAR) NOT NULL CHECK (priority IN ('LOW','MEDIUM','HIGH')),
    assignee_id NUMBER(19) REFERENCES reference_user(id),
    author_id NUMBER(19) NOT NULL REFERENCES reference_user(id),
    due_date VARCHAR2(10 CHAR),
    tags_json VARCHAR2(2000 CHAR) DEFAULT '[]' NOT NULL,
    position BINARY_DOUBLE NOT NULL,
    revision NUMBER(10) DEFAULT 1 NOT NULL CHECK (revision >= 1),
    command_sequence NUMBER(19) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP(6) WITH TIME ZONE,
    UNIQUE (board_id,status,position)
);
CREATE INDEX kanban_task_author ON kanban_task(board_id,author_id,status,position);
CREATE INDEX kanban_task_assignee ON kanban_task(board_id,assignee_id,status,position);
CREATE INDEX kanban_task_priority ON kanban_task(board_id,priority,status,position);
CREATE TABLE kanban_notice (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200 CHAR) NOT NULL CHECK (LENGTH(title) BETWEEN 1 AND 200),
    content CLOB NOT NULL,
    author_id NUMBER(19) NOT NULL REFERENCES reference_user(id),
    revision NUMBER(10) DEFAULT 1 NOT NULL CHECK (revision >= 1),
    command_sequence NUMBER(19) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX kanban_notice_created ON kanban_notice(created_at DESC,id DESC);
CREATE TABLE reference_document (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200 CHAR) NOT NULL,
    document_json CLOB NOT NULL,
    author_id NUMBER(19) NOT NULL REFERENCES reference_user(id),
    revision NUMBER(10) DEFAULT 1 NOT NULL CHECK (revision >= 1),
    command_sequence NUMBER(19) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX reference_document_author ON reference_document(author_id,updated_at DESC,id DESC);
