-- 앱 소유 oracle 새 스키마 DDL. 기존 H2 migration은 별도 경로에서 checksum을 보존한다.
CREATE TABLE starter_note (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200 CHAR) NOT NULL,
    owner VARCHAR2(64 CHAR) NOT NULL,
    revision NUMBER(10) DEFAULT 1 NOT NULL CHECK (revision>=1),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_starter_note_owner_updated ON starter_note(owner,updated_at DESC,id DESC);
