-- 앱 소유 postgresql 새 스키마 DDL. 기존 H2 migration은 별도 경로에서 checksum을 보존한다.
CREATE TABLE security_audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_subject VARCHAR(64) NOT NULL,
    actor_id BIGINT,
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    action VARCHAR(64) NOT NULL,
    outcome VARCHAR(7) NOT NULL CHECK (outcome IN ('SUCCESS', 'FAILURE', 'DENIED')),
    resource_type VARCHAR(32) NOT NULL,
    resource_id VARCHAR(128),
    request_id VARCHAR(64),
    reason_code VARCHAR(64),
    CHECK (actor_id IS NULL OR actor_id > 0),
    CHECK (actor_subject ~ '^[A-Za-z0-9._@-]{1,64}$'),
    CHECK (action ~ '^[A-Z][A-Z0-9_]{0,63}$'),
    CHECK (resource_type ~ '^[A-Z][A-Z0-9_]{0,31}$'),
    CHECK (resource_id IS NULL OR resource_id ~ '^[A-Za-z0-9._:-]{1,128}$'),
    CHECK (request_id IS NULL OR request_id ~ '^[A-Za-z0-9_-]{1,64}$'),
    CHECK (reason_code IS NULL OR reason_code ~ '^[A-Z][A-Z0-9_]{0,63}$')
);
CREATE INDEX idx_security_audit_latest ON security_audit_event(occurred_at DESC, id DESC);
CREATE INDEX idx_security_audit_filter ON security_audit_event(action, outcome, occurred_at DESC);
