-- 앱 소유 oracle 새 스키마 DDL. 기존 H2 migration은 별도 경로에서 checksum을 보존한다.
CREATE TABLE security_audit_event (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_subject VARCHAR2(64 CHAR) NOT NULL,
    actor_id NUMBER(19),
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    action VARCHAR2(64 CHAR) NOT NULL,
    outcome VARCHAR2(7 CHAR) NOT NULL CHECK (outcome IN ('SUCCESS', 'FAILURE', 'DENIED')),
    resource_type VARCHAR2(32 CHAR) NOT NULL,
    resource_id VARCHAR2(128 CHAR),
    request_id VARCHAR2(64 CHAR),
    reason_code VARCHAR2(64 CHAR),
    CHECK (actor_id IS NULL OR actor_id > 0),
    CHECK (REGEXP_LIKE(actor_subject, '^[A-Za-z0-9._@-]{1,64}$')),
    CHECK (REGEXP_LIKE(action, '^[A-Z][A-Z0-9_]{0,63}$')),
    CHECK (REGEXP_LIKE(resource_type, '^[A-Z][A-Z0-9_]{0,31}$')),
    CHECK (resource_id IS NULL OR REGEXP_LIKE(resource_id, '^[A-Za-z0-9._:-]{1,128}$')),
    CHECK (request_id IS NULL OR REGEXP_LIKE(request_id, '^[A-Za-z0-9_-]{1,64}$')),
    CHECK (reason_code IS NULL OR REGEXP_LIKE(reason_code, '^[A-Z][A-Z0-9_]{0,63}$'))
);
CREATE INDEX idx_security_audit_latest ON security_audit_event(occurred_at DESC, id DESC);
CREATE INDEX idx_security_audit_filter ON security_audit_event(action, outcome, occurred_at DESC);
