CREATE TABLE example_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT example_title_nonblank CHECK (CHAR_LENGTH(TRIM(title)) > 0),
    CONSTRAINT example_revision_positive CHECK (revision >= 1)
);
