/**
 * 공통 번역 사전과 이 앱의 app namespace를 연결한다. Java ResourceBundle처럼 키로 문구를 찾되 locale 변경 시 화면도 반응형으로 갱신된다.
 * UI 문구만 번역한다. API 경로·상태 코드·업무 ID를 표시 언어에 맞춰 바꾸지 않는다.
 */
import { createScI18n } from "@sc/i18n";
export const i18n = createScI18n({
  messages: {
    ko: {
      date: {
        title: "날짜 표시 예제",
        hint: "달력 날짜와 서버 UTC 시각의 의미를 구분합니다.",
        calendar: "달력 날짜",
        timestamp: "UTC 시각 원문",
        zone: "표시 시간대",
        locale: "날짜 언어",
        calendarResult: "달력 날짜 표시",
        timestampResult: "시각 표시",
        raw: "보존한 원문",
        validity: "UTC 원문 검사",
        scope:
          "이 예제는 입력을 서버에 저장하지 않습니다. 소수초 원문은 보존하고 시간대는 표시만 변경합니다.",
      },
      app: {
        reference: "레퍼런스",
        navigation: "화면 탐색",
        examples: "예제 목록",
        login: "로그인",
        logout: "로그아웃",
        start: "프로젝트 시작",
        operations: "운영 예제",
        patterns: "공통 기능 예제",
        footer: "공통 모듈을 사용해 화면을 조립합니다.",
        form: "공통 입력 폼",
        title: "제목",
        category: "유형",
        description: "설명",
        accepted: "검토 내용 확인",
        analysis: "분석",
        development: "개발",
        required: "입력해 주세요.",
        acceptRequired: "검토 내용을 확인해 주세요.",
        maxTitle: "제목은 200자 이하여야 합니다.",
        saved: "로컬 검증을 완료했습니다.",
        leave: "저장하지 않은 입력을 버리고 화면을 이동할까요?",
        lineChart: "선 그래프로",
        barChart: "막대 그래프로",
        discard: "작성 중인 입력을 초기화할까요?",
        confirmTitle: "입력 초기화 확인",
        formHint: "폼 상태와 Zod 검증은 이 화면이 소유합니다.",
        table: "정렬·페이지·선택 예제",
        largeTable: "가상 표 10,000행",
        largeList: "가상 목록 10,000행",
        name: "이름",
        amount: "수량",
        chart: "중립 차트",
        chartSummary: "합성 자료 3개의 값을 표로도 확인할 수 있습니다.",
        changeData: "자료 변경",
        selectDatum: "항목 선택",
        selectedDatum: "선택한 항목",
        editor: "서식 입력",
        excel: "엑셀 가져오기·내보내기",
        excelFile: "XLSX 파일",
        staged: "미리보기 자료",
        apply: "예제 자료에 반영",
        clear: "가져오기 취소",
        excelScope: "화면의 예제 자료만 내보냅니다. 서버에 저장하지 않습니다.",
        formNote: "이 예제는 로컬 검증이며 API 저장은 예제 목록 화면에서 확인합니다.",
      },
    },
    en: {
      date: {
        title: "Date display examples",
        hint: "Calendar dates and server UTC instants have different meanings.",
        calendar: "Calendar date",
        timestamp: "Raw UTC timestamp",
        zone: "Display time zone",
        locale: "Date locale",
        calendarResult: "Calendar display",
        timestampResult: "Timestamp display",
        raw: "Preserved input",
        validity: "UTC validation",
        scope:
          "No server write. Fractional seconds are preserved in the raw input; the time zone changes the display only.",
      },
      app: {
        reference: "Reference",
        navigation: "Navigation",
        examples: "Examples",
        login: "Sign in",
        logout: "Sign out",
        start: "Get started",
        operations: "Operations examples",
        patterns: "Common feature examples",
        footer: "Compose screens with shared modules.",
        form: "Shared input form",
        title: "Title",
        category: "Category",
        description: "Description",
        accepted: "Review acknowledged",
        analysis: "Analysis",
        development: "Development",
        required: "Please enter a value.",
        acceptRequired: "Please acknowledge the review.",
        maxTitle: "Title must be 200 characters or fewer.",
        saved: "Local validation completed.",
        leave: "Discard the draft and leave this screen?",
        lineChart: "Line chart",
        barChart: "Bar chart",
        discard: "Reset the draft?",
        confirmTitle: "Confirm draft reset",
        formHint: "This screen owns form state and Zod validation.",
        table: "Sorting, pagination and selection",
        largeTable: "Virtual table: 10,000 rows",
        largeList: "Virtual list: 10,000 rows",
        name: "Name",
        amount: "Quantity",
        chart: "Sample chart",
        chartSummary: "The three sample values are also available in a table.",
        changeData: "Change data",
        selectDatum: "Select datum",
        selectedDatum: "Selected datum",
        editor: "Rich text input",
        excel: "Excel import and export",
        excelFile: "XLSX file",
        staged: "Import preview",
        apply: "Apply to sample data",
        clear: "Cancel import",
        excelScope: "Export the supplied sample rows only. No server write.",
        formNote: "This example validates locally. Use Examples for API saving.",
      },
    },
  },
});
