-- Quartz 2.5.2 Apache-2.0 vendor DDL: https://raw.githubusercontent.com/quartz-scheduler/quartz/v2.5.2/quartz/src/main/resources/org/quartz/impl/jdbcjobstore/tables_db2_v95.sql
-- Flyway owns initialization; upstream DROP/DELETE/USE/COMMIT are excluded.
create table qrtz_job_details(
sched_name varchar(120) not null,
job_name varchar(80) not null,
job_group varchar(80) not null,
description varchar(120),
job_class_name varchar(128) not null,
is_durable integer not null,
is_nonconcurrent integer not null,
is_update_data integer not null,
requests_recovery integer not null,
job_data blob(2000),
primary key (sched_name,job_name,job_group)
);

create table qrtz_triggers(
sched_name varchar(120) not null,
trigger_name varchar(80) not null,
trigger_group varchar(80) not null,
job_name varchar(80) not null,
job_group varchar(80) not null,
description varchar(120),
next_fire_time bigint,
prev_fire_time bigint,
priority integer,
trigger_state varchar(16) not null,
trigger_type varchar(8) not null,
start_time bigint not null,
end_time bigint,
calendar_name varchar(80),
misfire_instr smallint,
job_data blob(2000),
primary key (sched_name,trigger_name,trigger_group),
foreign key (sched_name,job_name,job_group) references qrtz_job_details(sched_name,job_name,job_group)
);

create table qrtz_simple_triggers(
sched_name varchar(120) not null,
trigger_name varchar(80) not null,
trigger_group varchar(80) not null,
repeat_count bigint not null,
repeat_interval bigint not null,
times_triggered bigint not null,
primary key (sched_name,trigger_name,trigger_group),
foreign key (sched_name,trigger_name,trigger_group) references qrtz_triggers(sched_name,trigger_name,trigger_group)
);

create table qrtz_cron_triggers(
sched_name varchar(120) not null,
trigger_name varchar(80) not null,
trigger_group varchar(80) not null,
cron_expression varchar(120) not null,
time_zone_id varchar(80),
primary key (sched_name,trigger_name,trigger_group),
foreign key (sched_name,trigger_name,trigger_group) references qrtz_triggers(sched_name,trigger_name,trigger_group)
);

CREATE TABLE qrtz_simprop_triggers
  (          
    sched_name varchar(120) not null,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    STR_PROP_1 VARCHAR(512),
    STR_PROP_2 VARCHAR(512),
    STR_PROP_3 VARCHAR(512),
    INT_PROP_1 INT,
    INT_PROP_2 INT,
    LONG_PROP_1 BIGINT,
    LONG_PROP_2 BIGINT,
    DEC_PROP_1 NUMERIC(13,4),
    DEC_PROP_2 NUMERIC(13,4),
    BOOL_PROP_1 VARCHAR(1),
    BOOL_PROP_2 VARCHAR(1),
    PRIMARY KEY (sched_name,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (sched_name,TRIGGER_NAME,TRIGGER_GROUP) 
    REFERENCES QRTZ_TRIGGERS(sched_name,TRIGGER_NAME,TRIGGER_GROUP)
);

create table qrtz_blob_triggers(
sched_name varchar(120) not null,
trigger_name varchar(80) not null,
trigger_group varchar(80) not null,
blob_data blob(2000),
primary key (sched_name,trigger_name,trigger_group),
foreign key (sched_name,trigger_name,trigger_group) references qrtz_triggers(sched_name,trigger_name,trigger_group)
);

create table qrtz_calendars(
sched_name varchar(120) not null,
calendar_name varchar(80) not null,
calendar blob(2000) not null,
primary key (calendar_name)
);

create table qrtz_fired_triggers(
sched_name varchar(120) not null,
entry_id varchar(95) not null,
trigger_name varchar(80) not null,
trigger_group varchar(80) not null,
instance_name varchar(80) not null,
fired_time bigint not null,
sched_time bigint not null,
priority integer not null,
state varchar(16) not null,
job_name varchar(80),
job_group varchar(80),
is_nonconcurrent integer,
requests_recovery integer,
primary key (sched_name,entry_id)
);

create table qrtz_paused_trigger_grps(
sched_name varchar(120) not null,
trigger_group varchar(80) not null,
primary key (sched_name,trigger_group)
);

create table qrtz_scheduler_state(
sched_name varchar(120) not null,
instance_name varchar(80) not null,
last_checkin_time bigint not null,
checkin_interval bigint not null,
primary key (sched_name,instance_name)
);

create table qrtz_locks(
sched_name varchar(120) not null,
lock_name varchar(40) not null,
primary key (sched_name,lock_name)
);

-- 앱 소유 db2 새 스키마 DDL. 기존 H2 migration은 별도 경로에서 checksum을 보존한다.
CREATE TABLE operation_schedule (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY,
 job_code VARCHAR(64 CODEUNITS32) NOT NULL UNIQUE,
 cron VARCHAR(120 CODEUNITS32) NOT NULL,
 time_zone VARCHAR(64 CODEUNITS32) NOT NULL,
 misfire_policy VARCHAR(10 CODEUNITS32) NOT NULL CHECK(misfire_policy IN('SKIP','FIRE_ONCE')),
 enabled BOOLEAN NOT NULL,
 revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>=1),
 created_by VARCHAR(64 CODEUNITS32) NOT NULL,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL
);
CREATE TABLE operation_job_run (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 schedule_id BIGINT NOT NULL REFERENCES operation_schedule(id),
 run_key VARCHAR(36 CODEUNITS32) NOT NULL UNIQUE,
 job_code VARCHAR(64 CODEUNITS32) NOT NULL,
 scheduled_at TIMESTAMP(6) NOT NULL,
 started_at TIMESTAMP(6) NOT NULL,
 completed_at TIMESTAMP(6),
 state VARCHAR(8 CODEUNITS32) NOT NULL CHECK(state IN('RUNNING','SUCCESS','FAILED')),
 reason_code VARCHAR(32 CODEUNITS32),
 attempt INTEGER NOT NULL CHECK(attempt>=1),
 run_owner VARCHAR(36 CODEUNITS32) NOT NULL,
 execution_token VARCHAR(36 CODEUNITS32) NOT NULL
);
CREATE INDEX operation_run_recent ON operation_job_run(started_at DESC,id DESC);
CREATE INDEX operation_run_schedule ON operation_job_run(schedule_id,started_at DESC,id DESC);
CREATE INDEX operation_run_retention ON operation_job_run(completed_at,id);
CREATE TABLE operation_pulse_effect (
 run_key VARCHAR(36 CODEUNITS32) PRIMARY KEY,
 occurred_at TIMESTAMP(6) NOT NULL
);
CREATE TABLE browser_error_group (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 fingerprint VARCHAR(64 CODEUNITS32) NOT NULL UNIQUE,
 app_version VARCHAR(64 CODEUNITS32) NOT NULL,
 source VARCHAR(9 CODEUNITS32) NOT NULL CHECK(source IN('VUE','WINDOW','REJECTION')),
 event_code VARCHAR(32 CODEUNITS32) NOT NULL CHECK(event_code IN('VUE_ERROR','WINDOW_ERROR','UNHANDLED_REJECTION','UNKNOWN_RUNTIME')),
 route_code VARCHAR(64 CODEUNITS32) NOT NULL,
 component_code VARCHAR(64 CODEUNITS32) NOT NULL CHECK(component_code='ROOT'),
 first_seen_at TIMESTAMP(6) NOT NULL,
 last_seen_at TIMESTAMP(6) NOT NULL,
 occurrence_count BIGINT NOT NULL CHECK(occurrence_count>=0)
);
CREATE INDEX browser_error_group_recent ON browser_error_group(last_seen_at DESC,id DESC);
CREATE TABLE browser_error_occurrence (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 group_id BIGINT NOT NULL REFERENCES browser_error_group(id),
 actor_id BIGINT,
 actor_subject VARCHAR(64 CODEUNITS32) NOT NULL,
 request_id VARCHAR(64 CODEUNITS32),
 occurred_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX browser_error_occurrence_group ON browser_error_occurrence(group_id,occurred_at DESC,id DESC);
CREATE INDEX browser_error_occurrence_retention ON browser_error_occurrence(occurred_at,id);
CREATE TABLE browser_error_receipt (
 client_event_id VARCHAR(36 CODEUNITS32) NOT NULL,
 actor_subject VARCHAR(64 CODEUNITS32) NOT NULL,
 fingerprint VARCHAR(64 CODEUNITS32) NOT NULL,
 received_at TIMESTAMP(6) NOT NULL,
 PRIMARY KEY(client_event_id,actor_subject)
);
CREATE INDEX browser_error_receipt_retention ON browser_error_receipt(received_at,client_event_id);
