-- 앱 소유 postgresql 새 스키마 DDL. 기존 H2 migration은 별도 경로에서 checksum을 보존한다.
CREATE TABLE reference_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    display_name VARCHAR(80) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(16) NOT NULL CHECK (role IN ('REQUESTER', 'REVIEWER', 'ADMIN')),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE TABLE menu_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES menu_entry(id),
    name VARCHAR(120) NOT NULL,
    sort_order INTEGER NOT NULL,
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1))
);
CREATE TABLE requirement_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id BIGINT NOT NULL REFERENCES menu_entry(id),
    title VARCHAR(200) NOT NULL,
    desired VARCHAR(20000) NOT NULL,
    reason VARCHAR(10000) NOT NULL,
    reference_text VARCHAR(10000) NOT NULL,
    similar INTEGER NOT NULL CHECK (similar IN (0, 1)),
    follow_parts VARCHAR(10000) NOT NULL,
    screen_version_id BIGINT CONSTRAINT requirement_screen_unbound CHECK (screen_version_id IS NULL),
    status VARCHAR(16) NOT NULL CHECK (status IN ('DRAFT','REQUESTED','NEEDS_INFO','REVIEWING','AGREED','ADO_LINKED')),
    revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
    command_sequence BIGINT NOT NULL DEFAULT 0,
    author_id BIGINT NOT NULL REFERENCES reference_user(id),
    assigned_reviewer_id BIGINT REFERENCES reference_user(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX requirement_visibility ON requirement_entry(status, author_id);
CREATE INDEX requirement_updated ON requirement_entry(updated_at DESC, id DESC);
CREATE INDEX requirement_menu ON requirement_entry(menu_id);
CREATE TABLE requirement_review (
    requirement_id BIGINT PRIMARY KEY REFERENCES requirement_entry(id),
    decision VARCHAR(16) NOT NULL CHECK (decision IN ('UNREVIEWED','POSSIBLE','CONDITIONAL','MORE_INFO','IMPOSSIBLE')),
    rationale VARCHAR(10000) NOT NULL,
    conditions VARCHAR(10000) NOT NULL,
    scope VARCHAR(10000) NOT NULL,
    exclusions VARCHAR(10000) NOT NULL,
    acceptance VARCHAR(10000) NOT NULL,
    estimate VARCHAR(16) NOT NULL CHECK (estimate IN ('UNKNOWN','SMALL','MEDIUM','LARGE')),
    reviewer_id BIGINT NOT NULL REFERENCES reference_user(id),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE TABLE requirement_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_id BIGINT NOT NULL REFERENCES requirement_entry(id),
    body VARCHAR(10000) NOT NULL,
    author_id BIGINT NOT NULL REFERENCES reference_user(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX requirement_comment_order ON requirement_comment(requirement_id, id);
CREATE TABLE requirement_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_id BIGINT NOT NULL REFERENCES requirement_entry(id),
    action VARCHAR(32) NOT NULL,
    before_json TEXT,
    after_json TEXT NOT NULL,
    actor_id BIGINT NOT NULL REFERENCES reference_user(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX requirement_history_order ON requirement_history(requirement_id, id DESC);
