package dev.scframework.autoconfigure;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import dev.scframework.autoconfigure.audit.AuditWriteDiagnostics;
import dev.scframework.autoconfigure.audit.JdbcSecurityAuditSink;
import dev.scframework.autoconfigure.audit.TransactionalSecurityAuditPublisher;
import dev.scframework.core.audit.SecurityAuditEvent;
import java.time.Instant;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.transaction.support.TransactionTemplate;

class SecurityAuditTransactionTest {
    @Test void commitRecordsAfterCompletionAndRollbackNeverRecordsSuccess() {
        var dataSource = dataSource();
        var jdbc = new JdbcTemplate(dataSource);
        createSchema(jdbc);
        jdbc.execute("CREATE TABLE business_fixture(id INTEGER PRIMARY KEY)");
        var manager = new DataSourceTransactionManager(dataSource);
        var publisher = new TransactionalSecurityAuditPublisher(new JdbcSecurityAuditSink(dataSource), manager, new AuditWriteDiagnostics());
        var transaction = new TransactionTemplate(manager);
        transaction.executeWithoutResult(status -> {
            jdbc.update("INSERT INTO business_fixture VALUES (1)");
            publisher.publish(event("SUCCESS"));
            assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM security_audit_event", Integer.class)).isZero();
        });
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM security_audit_event", Integer.class)).isEqualTo(1);
        transaction.executeWithoutResult(status -> {
            jdbc.update("INSERT INTO business_fixture VALUES (2)");
            publisher.publish(event("SUCCESS"));
            publisher.publish(event("FAILURE"));
            status.setRollbackOnly();
        });
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM business_fixture", Integer.class)).isEqualTo(1);
        assertThat(jdbc.queryForList("SELECT outcome FROM security_audit_event ORDER BY id", String.class))
                .containsExactly("SUCCESS", "FAILURE");
        publisher.publish(event("DENIED"));
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM security_audit_event", Integer.class)).isEqualTo(3);
    }

    @Test void committedBusinessResultSurvivesSinkFailureWithOperationalSignal() {
        var dataSource = dataSource();
        var jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE business_fixture(id INTEGER PRIMARY KEY)");
        var manager = new DataSourceTransactionManager(dataSource);
        var diagnostics = new AuditWriteDiagnostics();
        var publisher = new TransactionalSecurityAuditPublisher(event -> { throw new IllegalStateException("synthetic-private-exception"); }, manager, diagnostics);
        String result = new TransactionTemplate(manager).execute(status -> {
            jdbc.update("INSERT INTO business_fixture VALUES (1)");
            publisher.publish(event("SUCCESS"));
            return "committed";
        });
        assertThat(result).isEqualTo("committed");
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM business_fixture", Integer.class)).isEqualTo(1);
        assertThat(diagnostics.getFailedWrites()).isEqualTo(1);
    }

    @Test void missingConsumerSchemaFailsWithoutGeneratingDdl() {
        var dataSource = dataSource();
        assertThatThrownBy(() -> new JdbcSecurityAuditSink(dataSource))
                .isInstanceOf(IllegalStateException.class).hasMessage("Audit storage schema is missing or unavailable");
        assertThat(new JdbcTemplate(dataSource).queryForObject("SELECT COUNT(*) FROM information_schema.tables WHERE table_name='SECURITY_AUDIT_EVENT'", Integer.class)).isZero();
    }

    private static SecurityAuditEvent event(String outcome) {
        return new SecurityAuditEvent("test-user", 1L, Instant.parse("2026-10-06T00:00:00Z"), "REQUIREMENT_UPDATE", outcome,
                "REQUIREMENT", "1", "req-1", "SUCCESS".equals(outcome) ? null : "INVALID_INPUT");
    }
    private static DriverManagerDataSource dataSource() {
        return new DriverManagerDataSource("jdbc:h2:mem:audit-" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1", "sa", "");
    }
    private static void createSchema(JdbcTemplate jdbc) {
        jdbc.execute("CREATE TABLE security_audit_event(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_subject VARCHAR(64),actor_id BIGINT,occurred_at TIMESTAMP(6) WITH TIME ZONE,action VARCHAR(64),outcome VARCHAR(7),resource_type VARCHAR(32),resource_id VARCHAR(128),request_id VARCHAR(64),reason_code VARCHAR(64))");
    }
}
