-- Quartz 2.5.2 Apache-2.0 vendor DDL: https://raw.githubusercontent.com/quartz-scheduler/quartz/v2.5.2/quartz/src/main/resources/org/quartz/impl/jdbcjobstore/tables_sqlServer.sql
-- Flyway owns initialization; upstream DROP/DELETE/USE/COMMIT are excluded.
CREATE TABLE [QRTZ_CALENDARS] (
  [SCHED_NAME] [NVARCHAR] (120)  NOT NULL ,
  [CALENDAR_NAME] [NVARCHAR] (200)  NOT NULL ,
  [CALENDAR] [VARBINARY] (max) NOT NULL
)
;
CREATE TABLE [QRTZ_CRON_TRIGGERS] (
  [SCHED_NAME] [NVARCHAR] (120)  NOT NULL ,
  [TRIGGER_NAME] [NVARCHAR] (200)  NOT NULL ,
  [TRIGGER_GROUP] [NVARCHAR] (200)  NOT NULL ,
  [CRON_EXPRESSION] [NVARCHAR] (120)  NOT NULL ,
  [TIME_ZONE_ID] [NVARCHAR] (80)
)
;
CREATE TABLE [QRTZ_FIRED_TRIGGERS] (
  [SCHED_NAME] [NVARCHAR] (120)  NOT NULL ,
  [ENTRY_ID] [NVARCHAR] (95)  NOT NULL ,
  [TRIGGER_NAME] [NVARCHAR] (200)  NOT NULL ,
  [TRIGGER_GROUP] [NVARCHAR] (200)  NOT NULL ,
  [INSTANCE_NAME] [NVARCHAR] (200)  NOT NULL ,
  [FIRED_TIME] [BIGINT] NOT NULL ,
  [SCHED_TIME] [BIGINT] NOT NULL ,
  [PRIORITY] [INTEGER] NOT NULL ,
  [STATE] [NVARCHAR] (16)  NOT NULL,
  [JOB_NAME] [NVARCHAR] (200)  NULL ,
  [JOB_GROUP] [NVARCHAR] (200)  NULL ,
  [IS_NONCONCURRENT] [NVARCHAR] (1)  NULL ,
  [REQUESTS_RECOVERY] [NVARCHAR] (1)  NULL
)
;
CREATE TABLE [QRTZ_PAUSED_TRIGGER_GRPS] (
  [SCHED_NAME] [NVARCHAR] (120)  NOT NULL ,
  [TRIGGER_GROUP] [NVARCHAR] (200)  NOT NULL
)
;
CREATE TABLE [QRTZ_SCHEDULER_STATE] (
  [SCHED_NAME] [NVARCHAR] (120)  NOT NULL ,
  [INSTANCE_NAME] [NVARCHAR] (200)  NOT NULL ,
  [LAST_CHECKIN_TIME] [BIGINT] NOT NULL ,
  [CHECKIN_INTERVAL] [BIGINT] NOT NULL
)
;
CREATE TABLE [QRTZ_LOCKS] (
  [SCHED_NAME] [NVARCHAR] (120)  NOT NULL ,
  [LOCK_NAME] [NVARCHAR] (40)  NOT NULL
)
;
CREATE TABLE [QRTZ_JOB_DETAILS] (
  [SCHED_NAME] [NVARCHAR] (120)  NOT NULL ,
  [JOB_NAME] [NVARCHAR] (200)  NOT NULL ,
  [JOB_GROUP] [NVARCHAR] (200)  NOT NULL ,
  [DESCRIPTION] [NVARCHAR] (250) NULL ,
  [JOB_CLASS_NAME] [NVARCHAR] (250)  NOT NULL ,
  [IS_DURABLE] [NVARCHAR] (1)  NOT NULL ,
  [IS_NONCONCURRENT] [NVARCHAR] (1)  NOT NULL ,
  [IS_UPDATE_DATA] [NVARCHAR] (1)  NOT NULL ,
  [REQUESTS_RECOVERY] [NVARCHAR] (1)  NOT NULL ,
  [JOB_DATA] [VARBINARY] (max) NULL
)
;
CREATE TABLE [QRTZ_SIMPLE_TRIGGERS] (
  [SCHED_NAME] [NVARCHAR] (120)  NOT NULL ,
  [TRIGGER_NAME] [NVARCHAR] (200)  NOT NULL ,
  [TRIGGER_GROUP] [NVARCHAR] (200)  NOT NULL ,
  [REPEAT_COUNT] [BIGINT] NOT NULL ,
  [REPEAT_INTERVAL] [BIGINT] NOT NULL ,
  [TIMES_TRIGGERED] [BIGINT] NOT NULL
)
;
CREATE TABLE [QRTZ_SIMPROP_TRIGGERS] (
  [SCHED_NAME] [NVARCHAR] (120)  NOT NULL ,
  [TRIGGER_NAME] [NVARCHAR] (200)  NOT NULL ,
  [TRIGGER_GROUP] [NVARCHAR] (200)  NOT NULL ,
  [STR_PROP_1] [NVARCHAR] (512) NULL,
  [STR_PROP_2] [NVARCHAR] (512) NULL,
  [STR_PROP_3] [NVARCHAR] (512) NULL,
  [INT_PROP_1] [INT] NULL,
  [INT_PROP_2] [INT] NULL,
  [LONG_PROP_1] [BIGINT] NULL,
  [LONG_PROP_2] [BIGINT] NULL,
  [DEC_PROP_1] [NUMERIC] (13,4) NULL,
  [DEC_PROP_2] [NUMERIC] (13,4) NULL,
  [BOOL_PROP_1] [NVARCHAR] (1) NULL,
  [BOOL_PROP_2] [NVARCHAR] (1) NULL,
)
;
CREATE TABLE [QRTZ_BLOB_TRIGGERS] (
  [SCHED_NAME] [NVARCHAR] (120)  NOT NULL ,
  [TRIGGER_NAME] [NVARCHAR] (200)  NOT NULL ,
  [TRIGGER_GROUP] [NVARCHAR] (200)  NOT NULL ,
  [BLOB_DATA] [VARBINARY] (max) NULL
)
;
CREATE TABLE [QRTZ_TRIGGERS] (
  [SCHED_NAME] [NVARCHAR] (120)  NOT NULL ,
  [TRIGGER_NAME] [NVARCHAR] (200)  NOT NULL ,
  [TRIGGER_GROUP] [NVARCHAR] (200)  NOT NULL ,
  [JOB_NAME] [NVARCHAR] (200)  NOT NULL ,
  [JOB_GROUP] [NVARCHAR] (200)  NOT NULL ,
  [DESCRIPTION] [NVARCHAR] (250) NULL ,
  [NEXT_FIRE_TIME] [BIGINT] NULL ,
  [PREV_FIRE_TIME] [BIGINT] NULL ,
  [PRIORITY] [INTEGER] NULL ,
  [TRIGGER_STATE] [NVARCHAR] (16)  NOT NULL ,
  [TRIGGER_TYPE] [NVARCHAR] (8)  NOT NULL ,
  [START_TIME] [BIGINT] NOT NULL ,
  [END_TIME] [BIGINT] NULL ,
  [CALENDAR_NAME] [NVARCHAR] (200)  NULL ,
  [MISFIRE_INSTR] [SMALLINT] NULL ,
  [JOB_DATA] [VARBINARY] (max) NULL
)
;
ALTER TABLE [QRTZ_CALENDARS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_CALENDARS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [CALENDAR_NAME]
  ) 
;
ALTER TABLE [QRTZ_CRON_TRIGGERS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_CRON_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) 
;
ALTER TABLE [QRTZ_FIRED_TRIGGERS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_FIRED_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [ENTRY_ID]
  ) 
;
ALTER TABLE [QRTZ_PAUSED_TRIGGER_GRPS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_PAUSED_TRIGGER_GRPS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_GROUP]
  ) 
;
ALTER TABLE [QRTZ_SCHEDULER_STATE] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_SCHEDULER_STATE] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [INSTANCE_NAME]
  ) 
;
ALTER TABLE [QRTZ_LOCKS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_LOCKS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [LOCK_NAME]
  ) 
;
ALTER TABLE [QRTZ_JOB_DETAILS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_JOB_DETAILS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [JOB_NAME],
    [JOB_GROUP]
  ) 
;
ALTER TABLE [QRTZ_SIMPLE_TRIGGERS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_SIMPLE_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) 
;
ALTER TABLE [QRTZ_SIMPROP_TRIGGERS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_SIMPROP_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) 
;
ALTER TABLE [QRTZ_TRIGGERS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) 
;
ALTER TABLE [QRTZ_CRON_TRIGGERS] ADD
  CONSTRAINT [FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS] FOREIGN KEY
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) REFERENCES [QRTZ_TRIGGERS] (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) ON DELETE CASCADE
;
ALTER TABLE [QRTZ_SIMPLE_TRIGGERS] ADD
  CONSTRAINT [FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS] FOREIGN KEY
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) REFERENCES [QRTZ_TRIGGERS] (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) ON DELETE CASCADE
;
ALTER TABLE [QRTZ_SIMPROP_TRIGGERS] ADD
  CONSTRAINT [FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS] FOREIGN KEY
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) REFERENCES [QRTZ_TRIGGERS] (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) ON DELETE CASCADE
;
ALTER TABLE [QRTZ_BLOB_TRIGGERS] ADD
  CONSTRAINT [FK_QRTZ_BLOB_TRIGGERS_QRTZ_TRIGGERS] FOREIGN KEY
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) REFERENCES [QRTZ_TRIGGERS] (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) ON DELETE CASCADE
;
ALTER TABLE [QRTZ_TRIGGERS] ADD
  CONSTRAINT [FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS] FOREIGN KEY
  (
    [SCHED_NAME],
    [JOB_NAME],
    [JOB_GROUP]
  ) REFERENCES [QRTZ_JOB_DETAILS] (
    [SCHED_NAME],
    [JOB_NAME],
    [JOB_GROUP]
  )
;
CREATE NONCLUSTERED INDEX [IX_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS] ON [QRTZ_CRON_TRIGGERS]
  (
    [SCHED_NAME] ASC,
    [TRIGGER_NAME] ASC,
    [TRIGGER_GROUP] ASC
  ) WITH (
    PAD_INDEX  = OFF,
    STATISTICS_NORECOMPUTE  = OFF,
    SORT_IN_TEMPDB = OFF,
    IGNORE_DUP_KEY = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS  = ON,
    ALLOW_PAGE_LOCKS  = ON
  )
;
CREATE NONCLUSTERED INDEX [IX_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS] ON [QRTZ_SIMPLE_TRIGGERS]
  (
    [SCHED_NAME] ASC,
    [TRIGGER_NAME] ASC,
    [TRIGGER_GROUP] ASC
  ) WITH (
    PAD_INDEX  = OFF,
    STATISTICS_NORECOMPUTE  = OFF,
    SORT_IN_TEMPDB = OFF,
    IGNORE_DUP_KEY = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS  = ON,
    ALLOW_PAGE_LOCKS  = ON
  )
;
CREATE NONCLUSTERED INDEX [IX_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS] ON [QRTZ_SIMPROP_TRIGGERS]
  (
    [SCHED_NAME] ASC,
    [TRIGGER_NAME] ASC,
    [TRIGGER_GROUP] ASC
  ) WITH (
    PAD_INDEX  = OFF,
    STATISTICS_NORECOMPUTE  = OFF,
    SORT_IN_TEMPDB = OFF,
    IGNORE_DUP_KEY = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS  = ON,
    ALLOW_PAGE_LOCKS  = ON
  )
;
CREATE NONCLUSTERED INDEX [IX_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS] ON [QRTZ_TRIGGERS]
  (
    [SCHED_NAME] ASC,
    [TRIGGER_NAME] ASC,
    [TRIGGER_GROUP] ASC
  ) WITH (
    PAD_INDEX  = OFF,
    STATISTICS_NORECOMPUTE  = OFF,
    SORT_IN_TEMPDB = OFF,
    IGNORE_DUP_KEY = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS  = ON,
    ALLOW_PAGE_LOCKS  = ON
  )
;

-- 앱 소유 sqlserver 새 스키마 DDL. 기존 H2 migration은 별도 경로에서 checksum을 보존한다.
CREATE TABLE operation_schedule (
 id BIGINT IDENTITY(100,1) PRIMARY KEY,
 job_code NVARCHAR(64) NOT NULL UNIQUE,
 cron NVARCHAR(120) NOT NULL,
 time_zone NVARCHAR(64) NOT NULL,
 misfire_policy NVARCHAR(10) NOT NULL CHECK(misfire_policy IN('SKIP','FIRE_ONCE')),
 enabled BIT NOT NULL,
 revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>=1),
 created_by NVARCHAR(64) NOT NULL,
 created_at DATETIMEOFFSET(6) NOT NULL,
 updated_at DATETIMEOFFSET(6) NOT NULL
);
CREATE TABLE operation_job_run (
 id BIGINT IDENTITY(1,1) PRIMARY KEY,
 schedule_id BIGINT NOT NULL REFERENCES operation_schedule(id),
 run_key NVARCHAR(36) NOT NULL UNIQUE,
 job_code NVARCHAR(64) NOT NULL,
 scheduled_at DATETIMEOFFSET(6) NOT NULL,
 started_at DATETIMEOFFSET(6) NOT NULL,
 completed_at DATETIMEOFFSET(6),
 state NVARCHAR(8) NOT NULL CHECK(state IN('RUNNING','SUCCESS','FAILED')),
 reason_code NVARCHAR(32),
 attempt INTEGER NOT NULL CHECK(attempt>=1),
 run_owner NVARCHAR(36) NOT NULL,
 execution_token NVARCHAR(36) NOT NULL
);
CREATE INDEX operation_run_recent ON operation_job_run(started_at DESC,id DESC);
CREATE INDEX operation_run_schedule ON operation_job_run(schedule_id,started_at DESC,id DESC);
CREATE INDEX operation_run_retention ON operation_job_run(completed_at,id);
CREATE TABLE operation_pulse_effect (
 run_key NVARCHAR(36) PRIMARY KEY,
 occurred_at DATETIMEOFFSET(6) NOT NULL
);
CREATE TABLE browser_error_group (
 id BIGINT IDENTITY(1,1) PRIMARY KEY,
 fingerprint NVARCHAR(64) NOT NULL UNIQUE,
 app_version NVARCHAR(64) NOT NULL,
 source NVARCHAR(9) NOT NULL CHECK(source IN('VUE','WINDOW','REJECTION')),
 event_code NVARCHAR(32) NOT NULL CHECK(event_code IN('VUE_ERROR','WINDOW_ERROR','UNHANDLED_REJECTION','UNKNOWN_RUNTIME')),
 route_code NVARCHAR(64) NOT NULL,
 component_code NVARCHAR(64) NOT NULL CHECK(component_code='ROOT'),
 first_seen_at DATETIMEOFFSET(6) NOT NULL,
 last_seen_at DATETIMEOFFSET(6) NOT NULL,
 occurrence_count BIGINT NOT NULL CHECK(occurrence_count>=0)
);
CREATE INDEX browser_error_group_recent ON browser_error_group(last_seen_at DESC,id DESC);
CREATE TABLE browser_error_occurrence (
 id BIGINT IDENTITY(1,1) PRIMARY KEY,
 group_id BIGINT NOT NULL REFERENCES browser_error_group(id),
 actor_id BIGINT,
 actor_subject NVARCHAR(64) NOT NULL,
 request_id NVARCHAR(64),
 occurred_at DATETIMEOFFSET(6) NOT NULL
);
CREATE INDEX browser_error_occurrence_group ON browser_error_occurrence(group_id,occurred_at DESC,id DESC);
CREATE INDEX browser_error_occurrence_retention ON browser_error_occurrence(occurred_at,id);
CREATE TABLE browser_error_receipt (
 client_event_id NVARCHAR(36) NOT NULL,
 actor_subject NVARCHAR(64) NOT NULL,
 fingerprint NVARCHAR(64) NOT NULL,
 received_at DATETIMEOFFSET(6) NOT NULL,
 PRIMARY KEY(client_event_id,actor_subject)
);
CREATE INDEX browser_error_receipt_retention ON browser_error_receipt(received_at,client_event_id);
