-- 앱 소유 db2 새 스키마 DDL. 기존 H2 migration은 별도 경로에서 checksum을 보존한다.
CREATE TABLE example_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200 CODEUNITS32) NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT example_title_nonblank CHECK (CHAR_LENGTH(TRIM(title)) > 0),
    CONSTRAINT example_revision_positive CHECK (revision >= 1)
);
