-- 앱 소유 db2 새 스키마 DDL. 기존 H2 migration은 별도 경로에서 checksum을 보존한다.
CREATE TABLE kanban_member (
    user_id BIGINT PRIMARY KEY REFERENCES reference_user(id)
);
CREATE TABLE kanban_board (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) PRIMARY KEY,
    title VARCHAR(100 CODEUNITS32) NOT NULL CHECK (CHAR_LENGTH(title) BETWEEN 1 AND 100),
    author_id BIGINT REFERENCES reference_user(id),
    revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
    command_sequence BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CHECK (id = 1 OR author_id IS NOT NULL)
);
INSERT INTO kanban_board(id,title,author_id,revision,created_at,updated_at)
VALUES (1,'기본 업무',NULL,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
CREATE TABLE kanban_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id BIGINT NOT NULL REFERENCES kanban_board(id),
    title VARCHAR(200 CODEUNITS32) NOT NULL,
    description CLOB(2M) NOT NULL DEFAULT '',
    status VARCHAR(16 CODEUNITS32) NOT NULL CHECK (status IN ('TODO','IN_PROGRESS','DONE','REJECTED')),
    priority VARCHAR(6 CODEUNITS32) NOT NULL CHECK (priority IN ('LOW','MEDIUM','HIGH')),
    assignee_id BIGINT REFERENCES reference_user(id),
    author_id BIGINT NOT NULL REFERENCES reference_user(id),
    due_date VARCHAR(10 CODEUNITS32),
    tags_json VARCHAR(2000 CODEUNITS32) NOT NULL DEFAULT '[]',
    position DOUBLE PRECISION NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
    command_sequence BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6),
    UNIQUE (board_id,status,position)
);
CREATE INDEX kanban_task_author ON kanban_task(board_id,author_id,status,position);
CREATE INDEX kanban_task_assignee ON kanban_task(board_id,assignee_id,status,position);
CREATE INDEX kanban_task_priority ON kanban_task(board_id,priority,status,position);
CREATE TABLE kanban_notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200 CODEUNITS32) NOT NULL CHECK (CHAR_LENGTH(title) BETWEEN 1 AND 200),
    content CLOB(2M) NOT NULL,
    author_id BIGINT NOT NULL REFERENCES reference_user(id),
    revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
    command_sequence BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX kanban_notice_created ON kanban_notice(created_at DESC,id DESC);
CREATE TABLE reference_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200 CODEUNITS32) NOT NULL,
    document_json CLOB(2M) NOT NULL,
    author_id BIGINT NOT NULL REFERENCES reference_user(id),
    revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
    command_sequence BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX reference_document_author ON reference_document(author_id,updated_at DESC,id DESC);
