CREATE TABLE starter_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    owner VARCHAR(64) NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1 CHECK (revision>=1),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_starter_note_owner_updated ON starter_note(owner,updated_at DESC,id DESC);
