-- 앱 소유 oracle 새 스키마 DDL. 기존 H2 migration은 별도 경로에서 checksum을 보존한다.
CREATE TABLE reference_user (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(64 CHAR) NOT NULL UNIQUE,
    display_name VARCHAR2(80 CHAR) NOT NULL,
    password_hash VARCHAR2(100 CHAR) NOT NULL,
    role VARCHAR2(16 CHAR) NOT NULL CHECK (role IN ('REQUESTER', 'REVIEWER', 'ADMIN')),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE TABLE menu_entry (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id NUMBER(19) REFERENCES menu_entry(id),
    name VARCHAR2(120 CHAR) NOT NULL,
    sort_order NUMBER(10) NOT NULL,
    active NUMBER(10) DEFAULT 1 NOT NULL CHECK (active IN (0, 1))
);
CREATE TABLE requirement_entry (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id NUMBER(19) NOT NULL REFERENCES menu_entry(id),
    title VARCHAR2(200 CHAR) NOT NULL,
    desired CLOB NOT NULL,
    reason CLOB NOT NULL,
    reference_text CLOB,
    similar NUMBER(10) NOT NULL CHECK (similar IN (0, 1)),
    follow_parts CLOB,
    screen_version_id NUMBER(19) CONSTRAINT requirement_screen_unbound CHECK (screen_version_id IS NULL),
    status VARCHAR2(16 CHAR) NOT NULL CHECK (status IN ('DRAFT','REQUESTED','NEEDS_INFO','REVIEWING','AGREED','ADO_LINKED')),
    revision NUMBER(10) DEFAULT 1 NOT NULL CHECK (revision >= 1),
    command_sequence NUMBER(19) DEFAULT 0 NOT NULL,
    author_id NUMBER(19) NOT NULL REFERENCES reference_user(id),
    assigned_reviewer_id NUMBER(19) REFERENCES reference_user(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX requirement_visibility ON requirement_entry(status, author_id);
CREATE INDEX requirement_updated ON requirement_entry(updated_at DESC, id DESC);
CREATE INDEX requirement_menu ON requirement_entry(menu_id);
CREATE TABLE requirement_review (
    requirement_id NUMBER(19) PRIMARY KEY REFERENCES requirement_entry(id),
    decision VARCHAR2(16 CHAR) NOT NULL CHECK (decision IN ('UNREVIEWED','POSSIBLE','CONDITIONAL','MORE_INFO','IMPOSSIBLE')),
    rationale CLOB NOT NULL,
    conditions CLOB,
    scope CLOB,
    exclusions CLOB,
    acceptance CLOB,
    estimate VARCHAR2(16 CHAR) NOT NULL CHECK (estimate IN ('UNKNOWN','SMALL','MEDIUM','LARGE')),
    reviewer_id NUMBER(19) NOT NULL REFERENCES reference_user(id),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE TABLE requirement_comment (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_id NUMBER(19) NOT NULL REFERENCES requirement_entry(id),
    body CLOB NOT NULL,
    author_id NUMBER(19) NOT NULL REFERENCES reference_user(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX requirement_comment_order ON requirement_comment(requirement_id, id);
CREATE TABLE requirement_history (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_id NUMBER(19) NOT NULL REFERENCES requirement_entry(id),
    action VARCHAR2(32 CHAR) NOT NULL,
    before_json CLOB,
    after_json CLOB NOT NULL,
    actor_id NUMBER(19) NOT NULL REFERENCES reference_user(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX requirement_history_order ON requirement_history(requirement_id, id DESC);
