-- 앱 소유 oracle 새 스키마 DDL. 기존 H2 migration은 별도 경로에서 checksum을 보존한다.
ALTER TABLE requirement_entry DROP CONSTRAINT requirement_screen_unbound;
CREATE TABLE stored_file (
 id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 storage_key VARCHAR2(36 CHAR) NOT NULL UNIQUE, original_name VARCHAR2(180 CHAR) NOT NULL,
 mime VARCHAR2(100 CHAR) NOT NULL, "SIZE" NUMBER(19) NOT NULL CHECK("SIZE">0),
 created_by NUMBER(19) NOT NULL REFERENCES reference_user(id), created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE TABLE screen_entry (
 id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 menu_id NUMBER(19) NOT NULL REFERENCES menu_entry(id), name VARCHAR2(200 CHAR) NOT NULL,
 next_version NUMBER(10) DEFAULT 1 NOT NULL CHECK(next_version>0)
);
CREATE TABLE screen_version (
 id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 screen_id NUMBER(19) NOT NULL REFERENCES screen_entry(id), version NUMBER(10) NOT NULL CHECK(version>0),
 file_id NUMBER(19) NOT NULL UNIQUE REFERENCES stored_file(id), width NUMBER(10) NOT NULL CHECK(width>0), height NUMBER(10) NOT NULL CHECK(height>0),
 created_by NUMBER(19) NOT NULL REFERENCES reference_user(id), created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
 archived NUMBER(10) DEFAULT 0 NOT NULL CHECK(archived IN(0,1)),
 next_annotation NUMBER(10) DEFAULT 1 NOT NULL CHECK(next_annotation>0), UNIQUE(screen_id,version)
);
ALTER TABLE requirement_entry ADD CONSTRAINT requirement_screen_version_fk FOREIGN KEY(screen_version_id) REFERENCES screen_version(id);
CREATE TABLE requirement_annotation (
 id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 requirement_id NUMBER(19) NOT NULL UNIQUE REFERENCES requirement_entry(id), screen_version_id NUMBER(19) NOT NULL REFERENCES screen_version(id),
 "NUMBER" NUMBER(10) NOT NULL CHECK("NUMBER">0), x BINARY_DOUBLE NOT NULL CHECK(x>=0 AND x<=1), y BINARY_DOUBLE NOT NULL CHECK(y>=0 AND y<=1),
 width BINARY_DOUBLE NOT NULL CHECK(width>0 AND width<=1), height BINARY_DOUBLE NOT NULL CHECK(height>0 AND height<=1),
 CHECK(x+width<=1.000000001 AND y+height<=1.000000001), UNIQUE(screen_version_id,"NUMBER")
);
CREATE TABLE requirement_attachment (
 id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 requirement_id NUMBER(19) NOT NULL REFERENCES requirement_entry(id), file_id NUMBER(19) NOT NULL UNIQUE REFERENCES stored_file(id),
 created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE TABLE requirement_ado (
 requirement_id NUMBER(19) PRIMARY KEY REFERENCES requirement_entry(id), ticket VARCHAR2(80 CHAR) NOT NULL, url VARCHAR2(2000 CHAR) NOT NULL,
 linked_by NUMBER(19) NOT NULL REFERENCES reference_user(id), linked_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
